"""This file should include only configuration values which can be parameterized for simulation"""
import math

NUMBER_OF_STEPS = 2

# User consts
INITIAL_RELATION_VALUE = 1
RELATION_DECAY_PER_CYCLE = 0.9
MIN_CHANCE_FOR_FRIENDS = 0.30

# Simulation consts
NUMBER_OF_USERS = 1000
MAX_NUMBER_OF_NEW_USERS = math.ceil(NUMBER_OF_USERS/500) + 1
NUMBER_OF_SIMULATION_STEPS = 10

# Group consts
MAX_NUMBER_OF_GROUPS = 10
NUMBER_OF_GROUP_STEPS = 10
NUMBER_OF_INIT_TRIES = 10
MIN_GROUP_CONSISTENCY = 0.1
USERS_SEARCHED_PER_ITERATION = 50
MAX_GROUP_MEMBERS = 0.5 * NUMBER_OF_USERS

# Roles consts
MODE_WITH_NEGOTIATIONS = "negotiations"
MODE_WITHOUT_NEGOTIATIONS = "no_negotiations"
CURR_MODE = MODE_WITH_NEGOTIATIONS
