# User consts
INITIAL_RELATION_VALUE = 1
RELATION_DECAY_PER_CYCLE = 0.9
MIN_CHANCE_FOR_FRIENDS = 0.015

# Post consts
TAGS = ["dog", "cat", "lama", "rabbit"]

# Simulation consts
NUMBER_OF_USERS = 10
NUMBER_OF_STEPS = 10
MAX_NUMBER_OF_GROUPS = 2

# Group consts
NUMBER_OF_GROUP_STEPS = 10
NUMBER_OF_INIT_TRIES = 10
MIN_GROUP_CONSISTENCY = 0.5
USERS_SEARCHED_PER_ITERATION = 5
MAX_GROUP_MEMBERS = 0.5 * NUMBER_OF_USERS

# Roles consts
MODE_WITH_NEGOTIATIONS = "negotiations"
MODE_WITHOUT_NEGOTIATIONS = "no_negotiations"
CURR_MODE = MODE_WITH_NEGOTIATIONS
